### PR TITLE
terraform: add repository for DockerFile.

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by the-maldridge** [comment]
Will we need multiple repos for building multiple containers?

**Comment by Gottox** [comment]
No, currently both https://hub.docker.com/r/gottox/voidlinux-musl and https://hub.docker.com/r/gottox/voidlinux are generated from https://github.com/gottox/void-docker.

**Comment by the-maldridge** [comment]
Will it be practical to also generate masterdir{-x86_64,i686}{-musl,} from the same repo?  Also is there a reason these files can't live in mklive?

**Comment by Gottox** [comment]
I can rearrange the Dockerfile to make use of void-mklive, That's a good idea!

**Comment by the-maldridge** [comment]
SGTM.  Lets leave this PR open until the files are pushed to mklive just in case.

**Pull request closed without merging**
