### PR TITLE
docs: Remove forum moderation docs

### PR DESCRIPTION
**Pull request by nilium**
Forums are gone, so this no longer applies.

### CODE REVIEW

**Comment by Vaelatern** [comment]
I don't see these as necessarily irrelevant.

It's a good guide and readily applicable to IRC.

**Comment by nilium** [comment]
I can do either. I suggested dropping it or repurposing it and was told to drop it, so if we want to close this and instead rewrite them to be social guidelines without forum references, that works too.

**Comment by Vaelatern** [comment]
Would you tag the person who recommended it? I don't feel strongly about my position.

**Comment by nilium** [comment]
That was from @the-maldridge after I brought it up on IRC (since the forums don't exist anymore).

**Comment by Vaelatern** [comment]
Scrolled back and read.

**Pull request merged**
