### PR TITLE
terraform: Remove @xtraeme from xbps

### PR DESCRIPTION
**Pull request by Vaelatern**
This is in reference to #67 

I am aware that a time for comments could be necessary according to the rules: https://infradocs.voidlinux.org/org/offboarding.html

However I'd like to not have this PR merged until Sunday to avoid heat-of-the-moment decisions.

### CODE REVIEW

**Comment by ahesford** [comment]
I'm confused. You declared your resignation and asked to be removed from the project. This is the start of a process to realize that.

**Comment by the-maldridge** [comment]
This was premature.  Converting to draft for now.

**Comment by Vaelatern** [comment]
Thank you for converting it to a draft. I must have missed the implications of that button.

**Comment by the-maldridge** [comment]
See comment in other thread.

**Comment by the-maldridge** [comment]
Held for review.

**Comment by Gottox** [comment]
I think we should follow @xtraeme wish for removal here. The other issue he raised https://github.com/void-linux/void-packages/issues/21303 will be discussed seperately.

**Pull request merged**
