### PR TITLE
terraform: Add @sgn as pkg committer

### PR DESCRIPTION
**Pull request by the-maldridge**
cc @pullmoll

### CODE REVIEW

**Comment by the-maldridge** [comment]
@sgn  Your work has caught the eye of a number of Void contributors, and we believe you are ready to make changes to the tree on your own.  This PR serves as the official offer to receive a commit bit for the void-packages tree.  You can signal you accept this offer by either reviewing this PR or by leaving a comment in the thread.

**Comment by sgn** [comment]
On 2020-04-18 13:24:31-0700, Michael Aldridge <notifications@github.com> wrote:
> @sgn  Your work has caught the eye of a number of Void contributors,
> and we believe you are ready to make changes to the tree on your
> own.  This PR serves as the official offer to receive a commit bit
> for the void-packages tree.  You can signal you accept this offer by
> either reviewing this PR or by leaving a comment in the thread.

I suppose this mean I will have the commit right in
`void-linux/void-packages`?

That'll be fine to me.

If it means I'll have another right, (and responsibility),
I'd need to know what is it.

-- 
Danh

**Comment by the-maldridge** [comment]
Primarily the void-packages repo, but this group grants you most of the auxiliary repos in the organization.  The expectation is that you continue to produce high quality work, and time permitting you lend your knowledge to review incoming patches.

**Comment by the-maldridge** [comment]
```
20:34 <maldridge> sgn: you basically get to work unsupervised once that PR is in
20:34 <maldridge> anything over that is your choice
20:35 <sgn> maldridge: That's OK to me
```

**Comment by Gottox** [comment]
Welcome on board! :woman_dancing:

**Pull request merged**
